### ISSUE TITLE
HRL SWF Error when checking minimum mapping length of vector+5m raster product

### ISSUE THREAD

**Issue by loic-faucqueur** [eea/copernicus_quality_tools#4]
Dear Team, 

I encounter an error when running QC tools (V1.5.2rc2, but error existed already on V1.5.2rc1) over certains Large Regions.

QC step vector.mml does not succeed nor fail, but gives this error message : 
`SYSTEM ERROR: Traceback (most recent call last): File "/usr/local/src/copernicus_quality_tools/src/qc_tool/worker/dispatch.py", line 149, in dispatch check_module.run_check(step_params, check_status) File "/usr/local/src/copernicus_quality_tools/src/qc_tool/vector/mml.py", line 42, in run_check cursor.execute(sql, sql_execute_params) psycopg2.InternalError: straight skeleton of Polygon with touching interior rings is not implemented`

Large regions concerned previously failed to pass the QC due to invalid geometry / multipart polygons. Correction of the geometries and multipart now led to this error.

Can you help us solving this ?

Thanks in advance !

Loïc

PS: FYI, an other issue prevent us to succesfully pass the QC on V1.4.3 for one LR : 

`SYSTEM ERROR: Traceback (most recent call last): File "/usr/local/src/copernicus_quality_tools/src/qc_tool/worker/dispatch.py", line 149, in dispatch check_module.run_check(step_params, check_status) File "/usr/local/src/copernicus_quality_tools/src/qc_tool/raster/gap.py", line 219, in run_check arr_mask_mapped = (arr_mask != nodata_value_mask).astype(int) AttributeError: 'bool' object has no attribute 'astype'`
However, this error seems to be solved on V1.5.2rc1 and V1.5.2rc2.

**Comment by igokr** [comment]
The MML check utilizes [`ST_ApproximateMedialAxis()`](https://postgis.net/docs/ST_ApproximateMedialAxis.html) function which then utilizes [`ST_StraightSkeleton()`](https://postgis.net/docs/ST_StraightSkeleton.html) function.
I have made a small test confirming the function `ST_StraightSkeleton()` gives such error in case described.
Although the geometry is valid, `ST_StraightSkeleton()` does not work in case of touching interior rings.

Solution.
The specification _HRL_LOT5_D5.1_Product Specification Document_I3-3.docx, Table 1: Geometric specifications of SWF_ states, the minimum mapping length check should be applied to linear structures.
In accord, the MML check is **in principle** related to linear structures.
Because linear structures may be curved, we can not simply utilize `ST_OrientedEnvelope()`, we must utilize `ST_ApproximateMedialAxis()`.
As the check concentrates just on linear structures, we may assume an attitude, that inner rings are irrelevant in such *linear* features.
Moreover, such inner rings may actually distort overall length of a feature.
So, we propose to ignore inner rings and apply `ST_ApproximateMedialAxis()` just on the outer ring.

**Comment by jirikadlec2** [comment]
The proposed adjustment which removes the system error has been implemented in QC Tool 1.5.8rc3 release candidate (https://github.com/eea/copernicus_quality_tools/releases/tag/1.5.8rc3), please test.

Thanks,
Jiří & Igor.

**Comment by loic-faucqueur** [comment]
Thanks a lot, we will test this asap !

**Comment by loic-faucqueur** [comment]
We have tested V1.5.8 and indeed, this new version solves this issue.

Many thanks for your support !
